"""empty message

Revision ID: 00776a8c1af9
Revises: 9a90d271884e
Create Date: 2021-11-26 09:36:33.081161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00776a8c1af9'
down_revision = '9a90d271884e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chocolate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_location', sa.String(length=64), nullable=False),
    sa.Column('country_of_bean_origin', sa.String(length=64), nullable=False),
    sa.Column('company_location_id', sa.String(), nullable=True),
    sa.Column('country_of_bean_origin_id', sa.String(), nullable=True),
    sa.Column('cocoa_percent', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_location_id'], ['countries.country_name'], ),
    sa.ForeignKeyConstraint(['country_of_bean_origin_id'], ['countries.country_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_table('chocolate')
    # ### end Alembic commands ###
