"""empty message

Revision ID: 28d47ecaa860
Revises: 8b5fc9f142ff
Create Date: 2021-11-24 13:27:26.010353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d47ecaa860'
down_revision = '8b5fc9f142ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'countries', ['country_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    # ### end Alembic commands ###
