"""empty message

Revision ID: 728aabf0eadc
Revises: 2559d39119cd
Create Date: 2021-11-26 10:25:34.192230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728aabf0eadc'
down_revision = '2559d39119cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chocolate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_location', sa.String(length=64), nullable=False),
    sa.Column('country_of_bean_origin', sa.String(length=64), nullable=False),
    sa.Column('company_location_id', sa.String(), nullable=True),
    sa.Column('country_of_bean_origin_id', sa.String(), nullable=True),
    sa.Column('cocoa_percent', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_location_id'], ['countries.country_name'], ),
    sa.ForeignKeyConstraint(['country_of_bean_origin_id'], ['countries.country_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chocolate')
    # ### end Alembic commands ###
