"""empty message

Revision ID: 8b5fc9f142ff
Revises: d6513a1581c7
Create Date: 2021-11-24 12:43:04.334855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5fc9f142ff'
down_revision = 'd6513a1581c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('gpd_capita', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('country_name'),
    sa.UniqueConstraint('country_name')
    )
    op.add_column('country_drinks_info', sa.Column('country_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'country_drinks_info', 'countries', ['country_id'], ['country_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country_drinks_info', type_='foreignkey')
    op.drop_column('country_drinks_info', 'country_id')
    op.drop_table('countries')
    # ### end Alembic commands ###
