"""empty message

Revision ID: 9a90d271884e
Revises: 28d47ecaa860
Create Date: 2021-11-24 14:18:07.614403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a90d271884e'
down_revision = '28d47ecaa860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_drinks_info', 'country_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_drinks_info', 'country_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
